apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  policyController:
    enabled: false
  git:
    secretType: ssh
    syncRepo: &syncRepo git@github.com:linde/acm-1.1-demo.git
    syncBranch: &syncBranch istio-multi
    policyDir: config-root
  clusterName: *syncBranch



