apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: submodule-test
  policyController:
    enabled: false
  git:
    secretType: ssh
    syncRepo: git@github.com:linde/acm-1.1-demo.git
    syncBranch: acm-git-submodule
    policyDir: config-root
