apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: nomos-empty
  policyController:
    enabled: true
  git:
    secretType: ssh
    syncRepo: git@github.com:linde/acm-1.1-demo.git
    policyDir: config-root
    syncBranch: poss-hydrate-issue
